spring:
   datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: ${DATABASE_DRIVER_CLASS}
   jpa:
      properties:
         hibernate:
            dialect: ${HIBERNATE_DIALECT}
      hibernate:
         ddl-auto: ${HIBERNATE_DDL_AUTO}

password:
   validation:
      regex: ${PASSWORD_VALIDATION_REGEX}

jwt:
   secret: ${JWT_SECRET}
   expiration: ${JWT_EXPIRATION}