spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/testdb
      username: postgres
      password: mysecretpassword
      driver-class-name: org.postgresql.Driver
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: update

password:
   validation:
      regex: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$

jwt:
   secret: YourSecretKey
   expiration: 3600000 # Token expiration time in milliseconds (1 hour by default)